<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>SpeechConverter.Entities</PackageId>
    <PackageVersion>1.2.0.0</PackageVersion>
    <ReleaseVersion>1.2.0.0</ReleaseVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <ProductVersion>1.2.0</ProductVersion>
    <Authors>Dave Walker</Authors>
    <Copyright>Copyright (c) 2026 Dave Walker</Copyright>
    <Owners>Dave Walker</Owners>
    <Title>Speech Converter Domain Models</Title>
    <Summary>Speech Converter Domain Models</Summary>
    <PackageTags>Speech Converter Entities</PackageTags>
    <Description>Speech Converter Domain Models/Entities</Description>
    <PackOnBuild>true</PackOnBuild>
    <PackageProjectUrl>https://github.com/davewalker5/RC2014</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
