<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>MIDIConverter.Entities</PackageId>
    <PackageVersion>1.0.0.0</PackageVersion>
    <ReleaseVersion>1.0.0.0</ReleaseVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <ProductVersion>1.0.0</ProductVersion>
    <Authors>Dave Walker</Authors>
    <Copyright>Copyright (c) 2026 Dave Walker</Copyright>
    <Owners>Dave Walker</Owners>
    <Title>MIDI Converter Domain Models</Title>
    <Summary>MIDI Converter Domain Models</Summary>
    <PackageTags>MIDI Converter Entities</PackageTags>
    <Description>MIDI Converter Domain Models/Entities</Description>
    <PackOnBuild>true</PackOnBuild>
    <PackageProjectUrl>https://github.com/davewalker5/RC2014</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

</Project>
