<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Renumber.Entities</PackageId>
    <PackageVersion>1.2.0.0</PackageVersion>
    <ReleaseVersion>1.2.0.0</ReleaseVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <ProductVersion>1.2.0</ProductVersion>
    <Authors>Dave Walker</Authors>
    <Copyright>Copyright (c) 2024 - 2026 Dave Walker</Copyright>
    <Owners>Dave Walker</Owners>
    <Title>BASIC Program Line Renumbering Domain Models</Title>
    <Summary>BASIC Program Line Renumbering Domain Models</Summary>
    <PackageTags>BASIC Line Number Renumber Domain Models Entities</PackageTags>
    <Description>BASIC Program Line Renumbering Domain Models</Description>
    <PackOnBuild>true</PackOnBuild>
    <PackageProjectUrl>https://github.com/davewalker5/RC2014</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

</Project>
