1000 REM Initialise the bat call pulse data. The values are
1010 REM generated by spectrogram inspection and pulse-
1020 REM level measurement. That process is described in
1030 REM the following links:
1040 REM https://fieldnotesjournal.uk/wildlife/batcalls/
1050 REM https://fieldnotesjournal.uk/wildlife/pocket/
1060 REM PRI = Pulse repetition interval
1070 REM DPRI = Change in PRI between adjacent pulses
1080 REM P() = PRI
1090 REM PV() = PRI validity, 1 = valid, 0 = invalid
1100 REM D() = Delta-PRI, DPRI
1110 REM DV() = DPRI validity, 1 = valid, 0 = invalid
1120 NP = 33 : DIM P(NP), PV(NP), D(NP), DV(NP)
1122 DIM PH$(NP), CL$(NP), PS(NP), PE(NP), PL(NP)
1130 REM Set all PRI and DPRI validities to "valid"
1140 FOR X = 1 TO NP
1150 LET PV(X) = 1 : LET DV(X) = 1
1160 NEXT X
1170 REM Read the PRI data
1180 RESTORE
1190 FOR X = 1 TO NP
1200 READ P(X)
1210 NEXT X
1220 REM Read the invalid PRI indicators
1230 READ I : IF I > NP THEN GOTO 1250
1240 LET PV(I) = 0 : GOTO 1230
1250 REM Read the DPRI data
1260 FOR X = 1 TO NP
1270 READ D(X)
1280 NEXT X
1290 REM Read the invalid DPRI indicators
1300 READ I : IF I <= NP THEN LET DV(I) = 0 : GOTO 1300
1310 REM PRI data
1320 DATA 0.0689, 0.0063, 0.002, 0.0042, 0.0052, 0.0027
1330 DATA 0.0416, 0.012, 0.022, 0.059, 0.009, 0.055, 0.011
1340 DATA 0.023, 0.002, 0.043, 0.016, 0.044, 0.017, 0.034
1350 DATA 0.015, 0.03, 0.019, 0.012, 0.02, 0.024, 0.008
1360 DATA 0.007, 0.007, 0.006, 0.012, 0.005, 0
1370 REM Invalid PRI indices
1380 DATA 33, 999
1390 REM DPRI data
1400 DATA 0, -0.0626, -0.0043, 0.0022, 0.001, -0.0025
1410 DATA 0.0389, -0.0296, 0.01, 0.037, -0.05, 0.046
1420 DATA -0.044, 0.012, -0.021, 0.041, -0.027, 0.028
1430 DATA -0.027, 0.017, -0.019, 0.015, -0.011, -0.007
1440 DATA 0.008, 0.004, -0.016, -0.001, 0.0, -0.001, 0.006
1450 DATA -0.007, 0
1460 REM Invalid DPRI indices
1470 DATA 1, 33, 999
1480 RETURN
