10 REM Analyse pulse-level bat call data to identify
20 REM search, approach and feeding buzz phases
30 PRINT
40 PRINT "BAT BEHAVIOURAL PHASE ANALYSIS"
50 PRINT "=============================="
60 PRINT
70 REM Initialise and tabulate the data
80 GOSUB 1000 : REM GOSUB 4000
90 REM Create an array of valid PRI values then sort them
100 REM and calculate the median of the more relaxed
110 REM (search phase) intervals to use as a baseline
120 GOSUB 2000 : GOSUB 2100
130 PRINT "Number of valid pulse intervals ="; NV
140 IF NV > 0 THEN GOSUB 2300
150 REM The upper median is now in UM
160 PRINT "Upper median PRI = "; UM
170 REM Detect phases and print the resulting regions
180 GOSUB 3300
190 IF NR = 0 THEN GOTO 210
200 GOSUB 5300
210 GOSUB 4500
220 PRINT : PRINT "Classification: "; FC$
230 END
1000 REM Initialise the bat call pulse data. The values are
1010 REM generated by spectrogram inspection and pulse-
1020 REM level measurement. That process is described in
1030 REM the following links:
1040 REM https://fieldnotesjournal.uk/wildlife/batcalls/
1050 REM https://fieldnotesjournal.uk/wildlife/pocket/
1060 REM PRI = Pulse repetition interval
1070 REM DPRI = Change in PRI between adjacent pulses
1080 REM P() = PRI
1090 REM PV() = PRI validity, 1 = valid, 0 = invalid
1100 REM D() = Delta-PRI, DPRI
1110 REM DV() = DPRI validity, 1 = valid, 0 = invalid
1120 NP = 33 : DIM P(NP), PV(NP), D(NP), DV(NP)
1122 DIM PH$(NP), CL$(NP), PS(NP), PE(NP), PL(NP)
1130 REM Set all PRI and DPRI validities to "valid"
1140 FOR X = 1 TO NP
1150 LET PV(X) = 1 : LET DV(X) = 1
1160 NEXT X
1170 REM Read the PRI data
1180 RESTORE
1190 FOR X = 1 TO NP
1200 READ P(X)
1210 NEXT X
1220 REM Read the invalid PRI indicators
1230 READ I : IF I > NP THEN GOTO 1250
1240 LET PV(I) = 0 : GOTO 1230
1250 REM Read the DPRI data
1260 FOR X = 1 TO NP
1270 READ D(X)
1280 NEXT X
1290 REM Read the invalid DPRI indicators
1300 READ I : IF I <= NP THEN LET DV(I) = 0 : GOTO 1300
1310 REM PRI data
1320 DATA 0.0689, 0.0063, 0.002, 0.0042, 0.0052, 0.0027
1330 DATA 0.0416, 0.012, 0.022, 0.059, 0.009, 0.055, 0.011
1340 DATA 0.023, 0.002, 0.043, 0.016, 0.044, 0.017, 0.034
1350 DATA 0.015, 0.03, 0.019, 0.012, 0.02, 0.024, 0.008
1360 DATA 0.007, 0.007, 0.006, 0.012, 0.005, 0
1370 REM Invalid PRI indices
1380 DATA 33, 999
1390 REM DPRI data
1400 DATA 0, -0.0626, -0.0043, 0.0022, 0.001, -0.0025
1410 DATA 0.0389, -0.0296, 0.01, 0.037, -0.05, 0.046
1420 DATA -0.044, 0.012, -0.021, 0.041, -0.027, 0.028
1430 DATA -0.027, 0.017, -0.019, 0.015, -0.011, -0.007
1440 DATA 0.008, 0.004, -0.016, -0.001, 0.0, -0.001, 0.006
1450 DATA -0.007, 0
1460 REM Invalid DPRI indices
1470 DATA 1, 33, 999
1480 RETURN
2000 REM Create an array of valid PRI values
2010 DIM VP(NP)
2020 LET NV = 0
2030 FOR X = 1 TO NP
2040 IF PV(X) = 1 THEN LET NV = NV + 1 : LET VP(NV) = P(X)
2050 NEXT X
2060 RETURN
2100 REM Sort valid PRI values in ascending order, in place
2110 REM using an "insertion sort". Scratch variables: SI,
2120 REM SJ and ST
2130 IF NV < 2 THEN RETURN
2140 FOR SI = 2 TO NV
2150 LET ST = VP(SI) : LET SJ = SI - 1
2160 IF SJ < 1 THEN GOTO 2200
2170 IF VP(SJ) <= ST THEN GOTO 2200
2180 LET VP(SJ+1) = VP(SJ) : LET SJ = SJ - 1
2190 GOTO 2160
2200 LET VP(SJ+1) = ST
2210 NEXT SI
2220 RETURN
2300 REM Calculate the median of the upper half of VP(),
2310 REM the valid PRI values. Recordings of bat call
2320 REM sequences may contain:
2330 REM - Very short PRI bursts
2340 REM - Buzz fragments
2350 REM - Dense calling
2360 REM - Pulse splitting
2370 REM - Heterodyne artefacts
2380 REM - Partial attack sequences
2390 REM Lots of tiny PRI values may make rapid calling look
2400 REM normal and cause the analysis to miss feeding
2410 REM buzzes. If VP() is sorted, the upper half will
2420 REM contain *longer* intervals and corresponds to more
2430 REM relaxed search behaviour. The median of those is
2440 REM a better baseline for detecting fast buzzes.
2450 LET HF = INT(NV / 2)
2460 LET NU = NV - HF
2470 LET MI = INT(NU / 2)
2480 IF NU - 2 * MI = 1 THEN UM = VP(HF + MI + 1) : RETURN
2490 LET UM = (VP(HF + MI) + VP(HF + MI + 1)) / 2
2500 RETURN
3000 REM Build phase regions from the phases PH$(). Each
3010 REM region is defined as a classification, CL$(), a
3020 REM start pulse index, PS(), and end pulse index,
3030 REM PE() and a region length, PL()
3040 REM Classification is one of SEARCH, APPROACH, BUZZ
3050 REM or EXIT
3060 REM Outputs: NR, CL$(), PS(), PE(), PL()
3070 REM Start/end pulse numbers are one-based, inclusive
3080 REM Caller dimensions all arrays to at least NP
3090 LET NR = 0
3100 IF NP < 1 THEN RETURN
3110 LET CP$ = PH$(1) : LET SP = 1
3120 IF NP = 1 THEN GOTO 3190
3130 FOR X = 2 TO NP
3140 IF PH$(X) = CP$ THEN GOTO 3180
3150 LET NR = NR + 1 : LET CL$(NR) = CP$
3160 LET PS(NR) = SP : LET PE(NR) = X - 1 : LET PL(NR) = X - SP
3170 LET SP = X : LET CP$ = PH$(X)
3180 NEXT X
3190 LET NR = NR + 1 : LET CL$(NR) = CP$
3200 LET PS(NR) = SP : LET PE(NR) = NP : LET PL(NR) = NP - SP + 1
3210 RETURN
3300 REM Detect behavioural phases within a bat pulse
3310 REM sequence using pulse timing structure, classifying
3320 REM each pulse as one of SEARCH, APPROACH, BUZZ or
3330 REM EXIT.
3340 REM Inputs:  NP, UM, P(), PV(), D(), DV()
3350 REM Outputs: PH$(), plus regions from subroutine 3000
3360 REM The caller must dimension input/output arrays to
3370 REM at least NP and UM must be calculated from the
3380 REM valid PRIs first
3390 LET NR = 0 : LET BF = 0
3400 IF NP < 1 THEN RETURN
3410 FOR I = 1 TO NP
3420 LET PH$(I) = "SEARCH"
3430 NEXT I
3440 IF NP < 6 THEN GOTO 4000
3450 REM No valid PRI means there is no baseline
3460 LET VC = 0
3470 FOR I = 1 TO NP
3480 IF PV(I) <> 0 THEN LET VC = VC + 1
3490 NEXT I
3500 IF VC = 0 THEN GOTO 4000
3510 LET BT = UM * 0.70 : LET AT = UM * 0.90
3520 LET RL = 0 : LET NC = 0 : LET SU = 0
3530 LET BF = 0
3540 REM Find and score runs of compressed PRIs
3550 FOR I = 1 TO NP
3560 IF PV(I) = 0 THEN GOTO 3640
3570 IF P(I) > BT THEN GOTO 3640
3580 IF RL > 0 THEN GOTO 3600
3590 LET RS = I
3600 LET RL = RL + 1 : LET SU = SU + P(I)
3610 IF DV(I) = 0 THEN GOTO 3660
3620 IF D(I) < 0 THEN LET NC = NC + 1
3630 GOTO 3660
3640 IF RL >= 4 THEN GOSUB 3930
3650 LET RL = 0 : LET NC = 0 : LET SU = 0
3660 NEXT I
3670 REM Catch a run reaching the end
3680 LET I = NP + 1
3690 IF RL >= 4 THEN GOSUB 3930
3700 IF BF = 0 THEN GOTO 4000
3710 REM Include the pulse following the final buzz PRI
3720 LET BE = BE + 1
3730 IF BE > NP THEN LET BE = NP
3740 FOR I = BS TO BE
3750 LET PH$(I) = "BUZZ"
3760 NEXT I
3770 REM Walk backwards to label the approach
3780 LET I = BS - 1
3790 IF I < 1 THEN GOTO 3870
3800 IF PV(I) = 0 THEN GOTO 3820
3810 IF P(I) <= AT THEN GOTO 3840
3820 IF DV(I) = 0 THEN GOTO 3870
3830 IF D(I) >= 0 THEN GOTO 3870
3840 LET PH$(I) = "APPROACH"
3850 LET I = I - 1
3860 GOTO 3790
3870 REM Label pulses after the buzz as exit
3880 IF BE >= NP THEN GOTO 4000
3890 FOR I = BE + 1 TO NP
3900 LET PH$(I) = "EXIT"
3910 NEXT I
3920 GOTO 4000
3930 REM Score current run; I is one past its final PRI
3940 LET SC = RL * 10 + NC * 2 + ((RS - 1) / NP) * 3 - SU / RL
3950 IF BF = 0 THEN GOTO 3970
3960 IF SC <= BC THEN RETURN
3970 LET BF = 1 : LET BC = SC
3980 LET BS = RS : LET BE = I - 1
3990 RETURN
4000 GOSUB 3000
4010 RETURN
4500 REM Classify the sequence from its phase regions
4510 REM Inputs: NR, CL$(), PL(). Output: FC$
4520 REM Scratch: CI, TP, NS, NA, NB, NE, SF
4530 LET TP = 0 : LET NS = 0 : LET NA = 0
4540 LET NB = 0 : LET NE = 0 : LET SF = 0
4550 LET FC$ = "MIXED OR UNCERTAIN PASS"
4560 IF NR < 1 THEN RETURN
4570 FOR CI = 1 TO NR
4580 LET TP = TP + PL(CI)
4590 IF CL$(CI) = "SEARCH" THEN LET NS = NS + PL(CI)
4600 IF CL$(CI) = "APPROACH" THEN LET NA = NA + PL(CI)
4610 IF CL$(CI) = "BUZZ" THEN LET NB = NB + PL(CI)
4620 IF CL$(CI) = "EXIT" THEN LET NE = NE + PL(CI)
4630 NEXT CI
4640 IF TP <> 0 THEN LET SF = NS / TP
4650 IF NB >= 6 AND NE >= 5 THEN GOTO 4730
4660 IF NB >= 6 THEN FC$ = "FEEDING BUZZ" : RETURN
4670 IF NB > 0 THEN FC$ = "SHORT OR WEAK BUZZ" : RETURN
4680 IF NA >= 5 THEN FC$ = "APPROACH WITHOUT BUZZ" : RETURN
4690 IF NA > 0 THEN FC$ = "BRIEF APPROACH ONLY" : RETURN
4700 IF SF >= 0.85 THEN FC$ = "SEARCH ONLY"
4710 RETURN
4730 LET FC$ = "FEEDING PASS WITH RECOVERY EXIT"
4740 RETURN
5000 REM Tabulate the PRI and DPRI data
5010 LET CW = 15 : PRINT
5020 REM Print PRI/DPRI table column headers
5030 LET PD$ = " "
5040 LET V$ = "Pulse" : GOSUB 6030 : PRINT " ";
5050 LET V$ = "PRI" : GOSUB 6030 : PRINT " ";
5060 LET V$ = "Validity" : GOSUB 6030 : PRINT " ";
5070 LET V$ = "DPRI" : GOSUB 6030 : PRINT " ";
5080 LET V$ = "Validity" : GOSUB 6030 : PRINT
5090 REM Print table header separator
5100 LET PD$ = "-"
5110 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5120 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5130 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5140 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5150 LET V$ = "-" : GOSUB 6030 : PRINT
5160 LET PD$ = " "
5170 REM Iterate over and tabulate PRI and DPRI
5180 FOR X = 1 TO NP
5190 LET V$ = STR$(X) : GOSUB 6000 : PRINT " ";
5200 LET V$ = STR$(P(X)) : GOSUB 6000 : PRINT " ";
5210 LET V$ = STR$(PV(X)) : GOSUB 6000 : PRINT " ";
5220 LET V$ = STR$(D(X)) : GOSUB 6000 : PRINT " ";
5230 LET V$ = STR$(DV(X)) : GOSUB 6000 : PRINT
5240 NEXT X
5250 RETURN
5300 REM Tabulate the regions
5310 LET CW = 15 : PRINT
5320 REM Print region table column headers
5330 LET PD$ = " "
5340 LET V$ = "Phase" : GOSUB 6030 : PRINT " ";
5350 LET V$ = "Start" : GOSUB 6030 : PRINT " ";
5360 LET V$ = "End" : GOSUB 6030 : PRINT " ";
5370 LET V$ = "Length" : GOSUB 6030 : PRINT
5380 REM Print table header separator
5390 LET PD$ = "-"
5400 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5410 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5420 LET V$ = "-" : GOSUB 6030 : PRINT " ";
5430 LET V$ = "-" : GOSUB 6030 : PRINT
5440 LET PD$ = " "
5450 REM Iterate over and tabulate the regions
5460 FOR X = 1 TO NR
5470 LET V$ = CL$(X) : GOSUB 6030 : PRINT " ";
5480 LET V$ = STR$(PS(X)) : GOSUB 6000 : PRINT " ";
5490 LET V$ = STR$(PE(X)) : GOSUB 6000 : PRINT " ";
5500 LET V$ = STR$(PL(X)) : GOSUB 6000 : PRINT
5510 NEXT X
5520 RETURN
6000 REM Numeric column: expand exponent before formatting
6010 IF LEFT$(V$,1) = " " THEN V$ = MID$(V$,2)
6020 GOSUB 6110
6030 REM Format and print one column
6040 IF LEFT$(V$,1) = " " THEN V$ = MID$(V$,2)
6050 IF LEN(V$) <= CW THEN GOTO 6080
6060 V$ = ""
6070 IF LEN(V$) < CW THEN V$ = V$ + "*" : GOTO 6070
6080 IF LEN(V$) < CW THEN V$ = PD$ + V$ : GOTO 6080
6090 PRINT V$;
6100 RETURN
6110 REM Expand STR$ exponent notation without rounding
6120 LET ZE = 1
6130 IF ZE > LEN(V$) THEN RETURN
6140 IF MID$(V$,ZE,1) <> "E" THEN ZE = ZE + 1 : GOTO 6130
6150 LET ZP = VAL(MID$(V$,ZE+1))
6160 LET ZM$ = LEFT$(V$,ZE-1) : LET ZS$ = ""
6170 IF LEFT$(ZM$,1) = "-" THEN ZS$ = "-" : ZM$ = MID$(ZM$,2)
6180 LET ZD$ = "" : LET ZB = LEN(ZM$)
6190 FOR ZI = 1 TO LEN(ZM$)
6200 LET ZC$ = MID$(ZM$,ZI,1)
6210 IF ZC$ = "." THEN ZB = LEN(ZD$) : GOTO 6230
6220 LET ZD$ = ZD$ + ZC$
6230 NEXT ZI
6240 LET ZP = ZB + ZP
6250 IF ZP > 0 THEN GOTO 6300
6260 IF ZP = 0 THEN GOTO 6290
6270 LET ZD$ = "0" + ZD$ : LET ZP = ZP + 1
6280 IF ZP < 0 THEN GOTO 6270
6290 LET V$ = ZS$ + "0." + ZD$ : RETURN
6300 IF ZP < LEN(ZD$) THEN GOTO 6330
6310 IF LEN(ZD$) < ZP THEN ZD$ = ZD$ + "0" : GOTO 6310
6320 LET V$ = ZS$ + ZD$ : RETURN
6330 LET V$ = ZS$ + LEFT$(ZD$,ZP) + "." + MID$(ZD$,ZP+1)
6340 RETURN
